### DISCUSSION TITLE
TriliumNext Server install

### DISCUSSION THREAD

**Discussion by doobes** [TriliumNext/Notes#396] [Q&A / Support] [answered]
Hi guys,

I realized that my existing Trilium server (on a RaspBerryPi) wasn't using my mapped NAS volume to store data in.

So seeing that the TriliumNext version is up and running, I've decided to try that.

I've got a shared volume on my NAS at //192.168.10.10/trilium/.  I can mount to it outside of docker easy peasy.  I've tried this with and without a mount outside of Docker.  Doesn't seem to make any difference.

I'm using a docker compose file and it looks like this:

```
services:
    trilium:
        image: 'triliumnext/notes:latest'
        container_name: trilium
        ports:
            - '8080:8080'
        volumes:
            - /NAS-trilium_data:/home/node/trilium-data
        restart: unless-stopped
volumes:
  NAS-trilium_data:
    driver_opts:
      type: "cifs"
      o: "username=username,password=password,uid=1000,gid=1000,file_mode=0777,dir_mode=0777,noexec,nosuid,nosetuids,nodev,vers=3.0"
      device: "//192.168.10.10/trilium/"
```

Running docker compose up, it all works without error.

But it's not using the NAS volume for data storage.

The compose stuff for the mount comes from here:

`https://random.blackpacket.net/2021/01/10/docker-nfs-and-cifs-volumes.html
`
Any thoughts?

thanks

chris

**Comment by doobes** [comment]
Ok,

This is kinda wierd

It put the data files in the root of the drive:

![image](https://github.com/user-attachments/assets/1c0cfe79-3265-427c-b867-affedb984a37)

It it's obviously not mounting the drive

**Reply by eliandoran** [reply]
@doobes ,

Can you try removing the forward slash of the volume mount?

```diff
        volumes:
-             - /NAS-trilium_data:/home/node/trilium-data
+             - NAS-trilium_data:/home/node/trilium-data
```

See https://forums.docker.com/t/docker-compose-mount-samba-volume/132407/6

**Comment by doobes** [comment]
Ok.

One step forward, one step sideways as they say.

Did as you suggested.  It didn't help that my password was incorrect in docker-compose.yml.

Sort all that out and now Trilium is erroring out:

 ```
✔ Network pi_default            Created                                                                                                                                          0.2s
 ✔ Volume "pi_NAS-trilium_data"  Created                                                                                                                                          0.0s
 ✔ Container trilium             Created                                                                                                                                          2.2s
Attaching to trilium
trilium  | No USER_UID specified, leaving 1000
trilium  | No USER_GID specified, leaving 1000
trilium  | (node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
trilium  | (Use `node --trace-warnings ...` to show where the warning was created)
trilium  | Generated session secret
trilium  |
trilium  |
trilium  | #
trilium  | # Fatal error in , line 0
trilium  | # Check failed: module->status() == kLinked || module->status() == kEvaluated.
trilium  | #
trilium  | #
trilium  | #
trilium  | #FailureMessage Object: 0x7fc003e7f0
trilium  | ----- Native stack trace -----
trilium  |
trilium  |  1: 0xd0e488  [node]
trilium  |  2: 0x1fb19e0 V8_Fatal(char const*, ...) [node]
trilium  |  3: 0x1384fe4 v8::internal::SourceTextModule::Evaluate(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SourceTextModule>) [node]
trilium  |  4: 0xed67d4 v8::Module::Evaluate(v8::Local<v8::Context>) [node]
trilium  |  5: 0xc517f0 node::loader::ModuleWrap::Evaluate(v8::FunctionCallbackInfo<v8::Value> const&) [node]
trilium  |  6: 0xf1e378 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [node]
trilium  |  7: 0xf1eb38  [node]
trilium  |  8: 0xf1ef50 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
trilium  |  9: 0x189c964  [node]
trilium  | Trace/breakpoint trap
trilium exited with code 0
```

It's writing files to the shared volume as I can see that from the Synology DSM app.

Thoughts?

**Reply by eliandoran** [reply]
@perfectra1n , can you have a look at this? This looks awfully similar to the issue we had in the previous versions.

@doobes , I see you are using `latest` but I'm not sure if you pulled the latest changes. Can you check on tag `v0.90.6-beta`?

**Reply by doobes** [reply]
Not sure how to do that.

**Reply by eliandoran** [reply]
@doobes , simply replace `'triliumnext/notes:latest'` with `'triliumnext/notes:v0.90.6-beta'` in your docker compose file.

**Reply by doobes** [reply]
Same result.  Trilium errors out.

docker-compose.yml file:

```
services:
    trilium:
        image: 'triliumnext/notes:v0.90.6-beta'
        container_name: trilium
        ports:
            - '8080:8080'
        volumes:
            - NAS-trilium_data:/home/node/trilium-data
        environment:
            - USER_UID=1000
            - USER_GID=1000
        restart: unless-stopped
volumes:
  NAS-trilium_data:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=username,password=password,uid=1000,gid=1000,vers=3.0"
      device: "//192.168.10.10/trilium"
```

Files are written to the mapped drive. But Trilium errors out and then repeatedly restarts.

**Reply by perfectra1n** [reply]
Yeah that certainly does seem to be the same issue as previous versions. Are you able to share the output of `neofetch` or some additional information about the Pi that you're using such as Model/OS/Architecture?

**Reply by eliandoran** [reply]
@doobes , for your information, the issue you have initially described seems to be #408 , which got solved by switching from SMB to NFS.

**Reply by doobes** [reply]
> @doobes , for your information, the issue you have initially described seems to be #408 , which got solved by switching from SMB to NFS.

or not

1) Mount the Docker volume:
```
sudo docker volume create --driver local \
  -o type=nfs \
  -o o=addr="192.168.10.10,rw,nfsvers=4" \
  -o device=:/volume1/trilium \
  nfs-trilium
```
2) Create/run the image:
sudo docker run -t -i -p 127.0.0.1:8080:8080 -v nfs-trilium:/home/node/trilium-data triliumnext/notes:v0.90.6-beta

`docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/nfs-trilium/_data': failed to mount local volume: mount :/volume1/trilium:/var/lib/docker/volumes/nfs-trilium/_data, data: addr=192.168.10.10,nfsvers=4: protocol not supported.`

I've got my NFS permissions set to accept connections from 172.18.0.0/24.

Trouble is, I don't know exactly what ip address Docker is creating.

This is the issue with NFS mounts./

Can we please fix the CIFS issue?

**Reply by perfectra1n** [reply]
The error `protocol not supported.` means that you will need to drop your `nfsvers=4` to `nfsvers=3`.

> Can we please fix the CIFS issue?

PRs are more than welcome @doobes :)

**Comment by doobes** [comment]
This is my current docker-compose.yml

```
services:
    trilium:
        image: 'triliumnext/notes:latest'
        container_name: trilium
        ports:
            - '8080:8080'
        volumes:
            - NAS-trilium_data:/home/node/trilium-data
        restart: unless-stopped
volumes:
  NAS-trilium_data:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=usename,password=password,uid=1000,gid=1000,vers=3.0"
      device: "//192.168.10.10/trilium"
```

**Comment by doobes** [comment]
Ok,

Just for fun, I deleted all the Docker stuff, volumes, containers, etc.

Mounted the shared folder on the NAS as /mnt/trilium

docker-compose.yml looks like this:


```
services:
    trilium:
        image: 'triliumnext/notes:latest'
        container_name: trilium
        ports:
            - '8080:8080'
        volumes:
            - /mnt/trilium:/home/node/trilium-data
        environment:
            - USER_UID=1000
            - USER_GID=1000
        restart: unless-stopped
```

It writes the files to /mnt/trilium, but I get the same error.
