### ISSUE TITLE
Admonitions have wrong icon/logo

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Notes#1524]
### Description

I've been really enjoying the new admonitions feature, however I've noticed that the warning and caution admonitions seem to have non-intuative icons/colors:

![Image](https://github.com/user-attachments/assets/d210f339-ba48-46b4-9771-0e4161c4415b)

Generally `caution` is associated with yellow and the caution sign, while `warnings` are associated with red and the error symbol.

Perhaps this is an upstream issue with CKEditor, if so, feel free to close this.

### TriliumNext Version

0.92.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11

**Comment by eliandoran** [comment]
@meichthys , the admonitions are at 1:1 parity (colors, types of admonitions, icons, even Markdown import/export) with GitHub's admonitions support, as documented here: https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/

The admonitions are pretty configurable via CSS:

```css
.admonition.note { --accent-color: #69c7ff; }
.admonition.tip { --accent-color: #40c025; }
.admonition.important { --accent-color: #9839f7; }
.admonition.caution { --accent-color: #ff2e2e; }
.admonition.warning { --accent-color: #e2aa03; }
```

In your case you could create an `#appCss` note with the following content:

```css
.admonition.warning { --accent-color: #ff2e2e; }
.admonition.caution { --accent-color: #e2aa03; }
```

> Perhaps this is an upstream issue with CKEditor, if so, feel free to close this.

Actually not, the admonitions are a feature exclusively implemented by us, as a custom plugin. 💪🏻
