### ISSUE TITLE
Option to always show the "Hoist note" button

### ISSUE THREAD

**Issue by VanHate** [TriliumNext/Notes#2354]
### Describe feature

Please consider adding an option to make the "Hoist note" button always visible, not only on hover over the workspace note. (For comparison, the "Unhoist" button is always shown.)
This would make it easier to visually locate the workspace note, especially when the tree is expanded and contains many notes.

**Comment by SiriusXT** [comment]
Nice idea! Here's a simple CSS snippet that will make the "Hoist note" button always visible:

```css
.tree .enter-workspace-button.bx.tree-item-button {
    display: block;
    order: 100;
}
```

For usage instructions, please refer to: https://github.com/TriliumNext/Notes/blob/develop/docs/User%20Guide/User%20Guide/Theme%20development/Custom%20app-wide%20CSS.md

I think small features like this could be provided through plugins. Once we have a plugin system, we'll offer these types of utilities through it.
