### ISSUE TITLE
(Feature request) Use mouse wheel to scroll up/down, instead of zoom in/out in mermaid notes

### ISSUE THREAD

**Issue by hasecilu** [TriliumNext/Notes#283]
### Describe feature

From https://github.com/zadam/trilium/issues/3335

I think this FR is relevant for a better UX on Mermaid diagrams.

### Additional Information

A good alternative could be to use:

- Scroll to zoom in/out
- Ctrl + Scroll to move vertically on the diagram viewport
- Shift + Scroll to move horizontally on the diagram viewport

**Comment by herrkami** [comment]
A Mermaid UX improvement would be great. Tbh, I find the default setting barely usable for charts larger than what fits into the div's height. 

The reason is that every new rendering resets the view to a top fraction, making editing other parts of the graph super cumbersome because you need to manually navigate to those after every single render. Since the width is already properly adjusted but the lower parts are hidden, users obviously and intuitively desire and expect the mouse wheel to scroll down. Instead they immediately run into the next annoyance when the chart gets zoomed in instead. 

A simple CSS workaround is to constrain the svg's height to the  div's, such that the entire graph is always shown:
```css
#root-widget .mermaid-render > svg {
  height: inherit;
}
```
You will conveniently see all your changes after each new render. The downside is sometimes that the details in very large graphs might become too tiny to be readable. In this case, however, zooming is exactly what you expect and want the mouse wheel to do.   

In this configuration, I find these additional adjustments quite useful: 

```css
#root-widget .component.split-note-container-widget .component .scrolling-container {
  flex-grow: 2 !important;  // slightly increase the height of the code editor
}

#root-widget .mermaid-render .grid .tick text {
  font-size: 14pt;
}

#root-widget .mermaid-render :is(.taskText, .taskTextOutsideRight, .taskTextOutsideLeft)  {
  font-size: 14pt;
}
```

Perhaps this helps a bit for now. :)
