### ISSUE TITLE
(Bug report) No docker images available for ARM machines, despite the documentation advertising their availability.

### ISSUE THREAD

**Issue by fvbommel** [TriliumNext/Notes#302]
### TriliumNext Version

v0.90.3

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 24.04: Linux pi4b 6.8.0-1008-raspi #8-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 16 19:17:49 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Description

According to the [Docker Server Installation for Trilium instructions](https://triliumnext.github.io/Docs/Wiki/docker-server-installation.html):
> Official docker images are published on docker hub for **AMD64, ARMv6, ARMv7 and ARMv8/64**: https://hub.docker.com/r/triliumnext/notes/

(emphasis added)

Unfortunately, this does not seem to be correct: I tried to install the docker image on my Raspberry Pi 4B, but got
> no matching manifest for linux/arm64/v8 in the manifest list entries

Clicking on the Docker Hub link above, I found only linux/amd64 images.

---

Looking for the GitHub workflows, I found a [docker.yaml](https://github.com/TriliumNext/Notes/blob/develop/.github/workflows_old/docker.yaml) in the `workflows_old` folder that should work with minor modifications to also push non-amd64 versions of the containers. Presumably this workflow is what `zadam/trilium` used to push the image I'm trying to upgrade from?

### Error logs

`$ cat docker-compose.yaml`
```yaml
version: '3.9'

services:
  trilium:
    image: triliumnext/notes:v0.90.3
    container_name: trilium
    hostname: trilium
    volumes:
      - ./data:/home/node/trilium-data
    restart: unless-stopped
```

`$ docker compose pull`  
`[+] Pulling 0/1`  
` ⠇ trilium Pulling                                                                                               1.9s `  
`no matching manifest for linux/arm64/v8 in the manifest list entries`
